### PR TITLE
fix(email): populate resource custom attribute values when loading re…

### LINKED ISSUE #1194: Resource custom attributes values are not added in email when a copy is sent via the reservation page.
[x]: This is a bug and not a question.

[x]: I understand that the best way to resolve this issue is to solve it and propose a Pull Request.

## Describe the bug**

When you create a reservation with custom attributes, the values appear in the email the user receive. 
When you open the same reservation on librebooking and use the More -> Email button to send a copy, the resource custom attributes values are missing (the label is showing only). 

## Screenshots**

Image

Image

## Specifications

  - LibreBooking version ( `develop` branch):

### PR DESCRIPTION
**Pull request by belcirelk**
…servation from DB

When loading an existing reservation series via ReservationRepository (e.g. the Email button flow), BookableResource objects were created with empty attributes. This caused all resource custom attribute values to appear blank in reservation emails, even though the attribute labels were visible.

Fix: collect resources in PopulateResources() and run GetAttributeValuesCommand for each one, mirroring the logic already used in ResourceRepository::LoadById(). This ensures attribute values are populated.

Closes: #1194

### CODE REVIEW

File: Domain/Access/ReservationRepository.php [hunk 1]
```diff
@@ -340,15 +340,33 @@ private function PopulateResources(ExistingReservationSeries $series)
...
             if ($row[ColumnNames::RESOURCE_LEVEL_ID] == ResourceLevel::Primary) {
                 $series->WithPrimaryResource($resource);
             } else {
                 $series->WithResource($resource);
             }
+            $resources[] = $resource;
         }
         $reader->Free();
+
+        // get all reservation resources attributes
```
Comment (JohnVillalovos) [inline Domain/Access/ReservationRepository.php]: Could this all be put inside the while loop on line 344? Then don't need to have a new `$resources` array.

Comment (belcirelk) [reply Domain/Access/ReservationRepository.php]: most likely yes. will update.

Comment (belcirelk) [reply Domain/Access/ReservationRepository.php]: Done. It was just easier to visualize for me the other way.

**Review by JohnVillalovos — APPROVED** [review]
Thanks @belcirelk 

LGTM
