### PR TITLE
fix: api group update will create a new group rather than updating the group

### LINKED ISSUE #375: API: Group update will create a new group rather than updating the group
Problem seems to be here:

https://github.com/LibreBooking/app/blob/3005fe20f372748274880d49fa424d71fdbcb67a/WebServices/Controllers/GroupSaveController.php#L149

Basically the `Update()` method is exactly the same as the `Create()` method

### PR DESCRIPTION
**Pull request by thanhdxuan**
When using APIs, I found this bug as @JohnVillalovos mentioned in #375. I tested locally and it works.

Closes: #375

### CODE REVIEW

**Comment by JohnVillalovos** [comment]
@thanhdxuan Thanks. I will try to test this.

File: WebServices/Controllers/GroupSaveController.php [hunk 1]
```diff
@@ -141,9 +141,9 @@ public function Update($groupId, $request, $session)
 
         $presenter = $this->GetPresenter(new CreateGroupFacade($request, $groupId));
 
-        $id = $presenter->AddGroup();
+        $presenter->AddGroup();
```
Comment (JohnVillalovos) [inline WebServices/Controllers/GroupSaveController.php]: It appears to still be creating a new group each time. So this seems wrong.

**Review by JohnVillalovos — CHANGES_REQUESTED** [review]

File: WebServices/Controllers/GroupSaveController.php (hunk 1 above)
Comment (thanhdxuan) [reply WebServices/Controllers/GroupSaveController.php]: Hi @JohnVillalovos, sorry for the mismatch. I forgot update the change to this PR, so I updated the statement to `$presenter->UpdateGroup();` in bb2e5ed.

Here his how I test this changes:

1. Build the docker image using https://github.com/LibreBooking/docker by:

```bash
# Update the refs to this MR

APP_GH_REF=refs/pull/767/head

# Build the docker image using **767 tag**
docker buildx build --no-cache\
  --build-arg APP_GH_REF=${APP_GH_REF} \
  --tag librebooking/librebooking:767 | sed -e "s/^v//") \
  --output type=docker \
  .
```
2. Run the container by `docker compose` (remember to change the image tag)
2. Install the app normally
3. Enable API and test by create a POST API to `Web/Services/Groups/:groupId`

The logs show updating group successfully.


[2025-11-04T11:59:30.635630+01:00] app.DEBUG: [User=  ()] **GroupsWriteWebService.Update() User=2, GroupId=2, Request={"name":"Thanh Dau Updated 2","isDefault":false}** [File=/var/www/html/WebServices/GroupsWriteWebService.php,Line=60] [] {"url":"/Web/Services/Groups/2","ip":"xxxxxx","http_method":"POST","server":"xxxx,"referrer":null}
[2025-11-04T11:59:30.635675+01:00] app.DEBUG: [User=  ()] **Renaming group id: 2 to: Thanh Dau Updated 2** [File=/var/www/html/Presenters/Admin/ManageGroupsPresenter.php,Line=265] [] {"url":"/Web/Services/Groups/2","ip":"xxxx","http_method":"POST","server":"xxx","referrer":null}
[2025-11-04T11:59:30.641276+01:00] app.DEBUG: [User=  ()] **GroupsWriteWebService.Update() - Group Updated.** GroupId=2 [File=/var/www/html/WebServices/GroupsWriteWebService.php,Line=65] [] {"url":"/Web/Services/Groups/2","ip":"xxxxx","http_method":"POST","server":"xxx","referrer":null}

**Review by JohnVillalovos — APPROVED** [review]
Thanks @thanhdxuan 

LGTM
