### PR TITLE
Fix api issue with new configkey validation

### LINKED ISSUE #805: [BUG] API Authentication broken by commit b81ba13acbae05469c46ab508ca5d1d3ed3f36d8
API Authentication no longer works after

```
Author: lucs7 <s0810498@gmail.com>
Date:   Sat Aug 2 11:04:24 2025 +0200

    feat: env support and config structure refactor

    1. Support for .env file loading via phpdotenv
        - Added EnvHelper to load environment variables
        - Example .env file provided in .env.example
        - Configurator now loads environment variables from .env

    2. Major restructure of config to nested array for main config and plugin configs
        - Renamed configs keys to be more consistent
        - Support of legacy structure and naming through ConfigKeys::$legacyKeyMap
        - Scheme and validation through ConfigKeys
        - Updated Configurator to use ConfigKeys for templating

    Example ConfigKeys
    public const APP_TITLE = [
        'key' => 'app.title',
        'legacy' => 'old.key',
        'type' => 'string',
        'default' => 'LibreBooking',
        'label' => 'App title',
        'description' => '...',
        'choices' => ['option 1' => 'Option 1', 'option 2' => 'Option 2'],
    ];
```

Maybe good to go to commit 8a05e8e7efecda77e7eef0f805b39035c080b330 to test as will get a 200 response for invalid credentials.

Can test this by doing:

```
curl -X POST -i \
  -H "Content-Type: application/json" \
  -d '{"username":"invalid_username","password":"invalid_password"}' \
  --no-location \
  "http://localhost/Web/Services/index.php/Authentication/Authenticate"
```

### PR DESCRIPTION
**Pull request by lucs7**
This pull request refactors how API group configuration is handled and improves error handling and logging consistency throughout the codebase. The main changes include centralizing configuration key usage, improving error messages, and standardizing log level values.

**Configuration and Error Handling Improvements:**

* Refactored all API group configuration lookups in `Web/Services/index.php` to use constants from `ConfigKeys` instead of string literals, ensuring consistency and reducing the risk of typos. [[1]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L101-R102) [[2]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L119-R121) [[3]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L142-R143) [[4]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L163-R164) [[5]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L180-R181) [[6]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L196-R197) [[7]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L210-R219) [[8]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L227-R228) [[9]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L252-R254)
* Updated the `GetConfigGroup` function to accept either a string or array config key, improved its documentation, and changed error handling to throw a `RuntimeException` with a clear message if the group cannot be found, instead of calling `die()`.
* Moved the API enabled check from the global scope to the Slim `slim.before.dispatch` hook, using `$app->halt()` with a `503 Service Unavailable` status code and a clear message when the API is disabled. [[1]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81L25-L27) [[2]](diffhunk://#diff-c966d0211b9c12b49dd812601ba838967e63b5d5019eb481d3ea331d2b542c81R46-R49)
* Updated the call to `AddCategory` in `RegisterAttributes` to use a named parameter for clarity.

**Logging Consistency:**

* Standardized logging level values in `ConfigKeys` to use lowercase (`debug`, `info`, `warning`, `error`) instead of uppercase, and updated descriptions accordingly.
* Ensured the log folder path in `Log.php` is always normalized by removing any trailing slash.

**HTTP Status Codes:**

* Added a `SERVICE_UNAVAILABLE` (503) constant to the `RestResponse` class for clearer and more maintainable HTTP responses.

Fixes #805

### CODE REVIEW

**Comment by JohnVillalovos** [comment]
Thanks @lucs7 but in my testing it still doesn't work. Now I am using the old config file. So maybe it is me as my Ansible role copies `config.devel.php`.

So my config file is this:

```
<?php

/** !!!!!!!!!!!! DEPRECATED !!!!!!!!!!!!!!!!!!
 * This file is deprecated and will be removed in a future release.
 * Please use config.dist.php instead and set $conf['settings']['app.debug'] = 'true';.
 * !!!!!!!!!!!! DEPRECATED !!!!!!!!!!!!!!!!!!
 */
$conf['settings']['inactivity.timeout'] = '527040';
$conf['settings']['api']['enabled'] = 'true';
$conf['settings']['logging']['folder'] = '/var/log/librebooking';
$conf['settings']['use.local.js.libs'] = 'true';               // false recommended, delivers jQuery from Google CDN, uses less bandwidth
$conf['settings']['default.timezone'] = 'America/Los_Angeles';
$conf['settings']['install.password'] = 'lb_install_passwd';
$conf['settings']['script.url'] = 'http://lb.example.com/Web';                           // public URL to the Web directory of this instance. this is the URL that appears when you are logging in. leave http: or https: off to auto-detect
ini_set('display_errors', 1);
```

But I get a 200 response when I attempt to login with the API, which just seems wrong.

File: lib/Config/ConfigKeys.php [hunk 1]
```diff
@@ -414,16 +414,16 @@ class ConfigKeys
...
         'choices' => [
             'none' => 'None',
-            'WARNING' => 'WARNING',
-            'ERROR' => 'ERROR',
-            'INFO' => 'INFO',
-            'DEBUG' => 'DEBUG',
+            'warning' => 'warning',
+            'error' => 'error',
+            'info' => 'info',
+            'debug' => 'debug',
```
Comment (JohnVillalovos) [inline lib/Config/ConfigKeys.php]: This seems like a breaking change?

What happens for users who are currently using the uppercase versions?

Comment (lucs7) [reply lib/Config/ConfigKeys.php]: Lets say its a bug fix as we always had it lowercase and i just mistyped it
The logic is now always converting to lowercase which is used in Log.php for the case check

**Review by JohnVillalovos — APPROVED** [review]
Thanks @lucs7
